package com.salman.dentalsystem.model.enums;

public enum ErrorCode {
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    PATIENT_NOT_FOUND,
    USER_NOT_FOUND,
    DOCTOR_NOT_FOUND,
    APPOINTMENT_NOT_FOUND,
    INVALID_APPOINTMENT_TIME,
    USER_ALREADY_ACTIVE,
    PATIENT_ALREADY_ACTIVE,
}
