package com.salman.dentalsystem.model.enums;

public enum ErrorCode {
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    PATIENT_NOT_FOUND,
    USER_NOT_FOUND,
    DENTIST_NOT_FOUND,
    APPOINTMENT_NOT_FOUND,
    INVALID_APPOINTMENT_TIME,
    USER_ALREADY_ACTIVE,
    PATIENT_ALREADY_ACTIVE,
    APPOINTMENT_CONFLICT,
    PATIENT_ALREADY_EXISTS,
    USER_ALREADY_EXISTS,
    INVALID_PAYMENT_AMOUNT,
    ACCESS_DENIED,
    UNAUTHORIZED,
    INVALID_PASSWORD,
    INVALID_REFRESH_TOKEN,
    REVOKED_REFRESH_TOKEN,
    EXPIRED_REFRESH_TOKEN,
    REFRESH_TOKEN_NOT_FOUND,
    UNAUTHORIZED_ACTION,
    PATIENT_NOT_ACTIVE,
    IMAGE_NOT_FOUND,
    INPUT_IS_MISSING
}
